<a href="https://colab.research.google.com/github/DESPI-Cj/58013-Linear-Algebra/blob/main/Long_Quiz_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

General Instructions:

On your Colab, name your activity as Long Quiz 1.ipynb and save a copy to your GitHub repository and don't forget to send the link here.
Using two different code cells, properly label each problem set.
Perform each operations in matrices using Python programming codes.

Problem 1. Consider the four matrices, (20 points each)

In [49]:
# a.) AB
#Note: dot product of A and B?
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [1,2],
    [3,4],
    [5,6]
])

AB = np.dot(A,B)
print("Dot product of matrices A and B")
print(np.matrix(AB))


Dot product of matrices A and B
[[22 28]
 [49 64]]


In [54]:
# b.) D + D.
import numpy as np
D = ([
    [1,2],
    [3,4]
])
print("Original Matrix:")
print(np.matrix(D))
print("When the matrix D + D is")
add = np.add(D,D)
print(np.matrix(add))



Original Matrix:
[[1 2]
 [3 4]]
When the matrix D + D is
[[2 4]
 [6 8]]


In [52]:
# c.) 2C
import numpy as np
C = ([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("Original Matrix:")
print(np.matrix(C))

C2 = np.multiply(C, 2)
print("When the matrix C is multiplie by 2 is")
print(np.matrix(C2))

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
When the matrix C is multiplie by 2 is
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


Problem 2. Find the cross-product of matrices, A = [2,7,4] and

B = [3,9,8]. Show your solutions using Python program . (40 points)

In [50]:
import numpy as np

A = ([2, 7, 4])
B = ([3,9,8])

AB = np.cross(A,B)
print("The cross-product of matrices A and B is")
print(np.matrix(AB))


The cross-product of matrices A and B is
[[20 -4 -3]]
