<a href="https://colab.research.google.com/github/DESPI-Cj/58013-Linear-Algebra/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. (20 points) Create a Multiplication Table/Chart of 1 to 10 using numpy/ python program.

In [11]:
import numpy as np
Multi_table = ([
    [1,2,3,4,5,6,7,8,9,10],
    [2,4,6,8,10,12,14,16,18,20],
    [3,6,9,12,15,18,21,24,27,30],
    [4,8,12,16,20,24,28,32,36,40],
    [5,10,15,20,25,30,35,40,45,50],
    [6,12,18,24,30,36,42,48,54,60],
    [7,14,21,28,35,42,49,56,63,70],
    [8,16,24,32,40,48,56,64,72,80],
    [9,18,27,36,45,54,63,72,81,90],
    [10,20,30,40,50,60,70,80,90,100]
])
print(np.matrix(Multi_table))


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Question 2. (10 points) In relation to Question 1, show a solution that doubles all the values of each element.

In [6]:
import numpy as np
Multi_table = ([
    [1,2,3,4,5,6,7,8,9,10],
    [2,4,6,8,10,12,14,16,18,20],
    [3,6,9,12,15,18,21,24,27,30],
    [4,8,12,16,20,24,28,32,36,40],
    [5,10,15,20,25,30,35,40,45,50],
    [6,12,18,24,30,36,42,48,54,60],
    [7,14,21,28,35,42,49,56,63,70],
    [8,16,24,32,40,48,56,64,72,80],
    [9,18,27,36,45,54,63,72,81,90],
    [10,20,30,40,50,60,70,80,90,100]
])

double = np.multiply(2,Multi_table)
print(double)


[[  2   4   6   8  10  12  14  16  18  20]
 [  4   8  12  16  20  24  28  32  36  40]
 [  6  12  18  24  30  36  42  48  54  60]
 [  8  16  24  32  40  48  56  64  72  80]
 [ 10  20  30  40  50  60  70  80  90 100]
 [ 12  24  36  48  60  72  84  96 108 120]
 [ 14  28  42  56  70  84  98 112 126 140]
 [ 16  32  48  64  80  96 112 128 144 160]
 [ 18  36  54  72  90 108 126 144 162 180]
 [ 20  40  60  80 100 120 140 160 180 200]]


Question 3. (10 points) Create a square matrix that has a diagonal 1's.



In [3]:
import numpy as np
array = np.eye(10,10)
print(array)




[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


Question 4. (30 points) Create a matrix whose elements are:

matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

Type a python program that can view the size, shape, and dimension of the matrix above.

In [14]:
import numpy as np
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print("View Matrix:")
print(matrix)
print("================================")
print("The size of the matrix is:",matrix.size)
print("The shape of the matrix is:",matrix.shape)
print("The dimension of the matrix is:",matrix.ndim)


View Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
The size of the matrix is: 12
The shape of the matrix is: (3, 4)
The dimension of the matrix is: 2


Question 5. (30 points) Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element.

In [9]:
import numpy as np
arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15,33,24],[4,7,1]])

result_array = np.add(arrayOne,arrayTwo)
print("The result when arrayOne + arrayTwo is:", "\n", result_array)
print("===========================================================")
squared = result_array**2
print("The answer when the result array's each element is squared:", "\n", squared)

The result when arrayOne + arrayTwo is: 
 [[20 39 33]
 [25 25 28]]
The answer when the result array's each element is squared: 
 [[ 400 1521 1089]
 [ 625  625  784]]
