<a href="https://colab.research.google.com/github/DESPI-Cj/58013-Linear-Algebra/blob/main/Python_Exercise_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([
    [1,4],
    [0,3]
])
np.linalg.det(A)

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([
    [1,3,5,6],
    [0,3,1,3],
    [3,1,8,2],
    [5,2,6,8]
])
np.linalg.det(B)



In [ ]:
#Assiociative Property
import numpy as np

# Define matrices A, B, and C
A = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
B = np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]])
C = np.array([[3, 0, 0], [0, 3, 0], [0, 0, 3]])

# Calculate A × (B × C)
result1 = np.dot(A, np.dot(B, C))

# Calculate (A × B) × C
result2 = np.dot(np.dot(A, B), C)

#Display matrices A,B,C
print("Matrice A")
print(A,"\n")
print("Matrice B")
print(B,"\n")
print("Matrice C")
print(C,"\n")

# Display the results
print("A × (B × C):")
print(result1)
print("\n(A × B) × C:")
print(result2)

# Check if the results are equal (associative property)
equal = np.array_equal(result1, result2)
print("Results are equal therefore:", equal)


Matrice A
[[1 0 0]
 [0 1 0]
 [0 0 1]] 

Matrice B
[[2 0 0]
 [0 2 0]
 [0 0 2]] 

Matrice C
[[3 0 0]
 [0 3 0]
 [0 0 3]] 

A × (B × C):
[[6 0 0]
 [0 6 0]
 [0 0 6]]

(A × B) × C:
[[6 0 0]
 [0 6 0]
 [0 0 6]]
Results are equal therefore: True


In [ ]:
#Distributive Property
import numpy as np

# Define 3x3 matrices A, B, and C
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
C = np.array([[19, 20, 21], [22, 23, 24], [25, 26, 27]])

# Calculate the products and the sum
product1 = np.dot(A, B + C)  # A * (B + C)
product2 = np.dot(A, B) + np.dot(A, C)  # A * B + A * C

#Display matrices A,B,C
print("Matrice A")
print(A,"\n")
print("Matrice B")
print(B,"\n")
print("Matrice C")
print(C,"\n")

# Display the results
print("A * (B + C):")
print(product1)
print("\nA * B + A * C:")
print(product2)

# Check if the results are equal (distributive property)
equal = np.array_equal(product1, product2)
print("Results are equal therefore:", equal)


Matrice A
[[1 2 3]
 [4 5 6]
 [7 8 9]] 

Matrice B
[[10 11 12]
 [13 14 15]
 [16 17 18]] 

Matrice C
[[19 20 21]
 [22 23 24]
 [25 26 27]] 

A * (B + C):
[[222 234 246]
 [537 567 597]
 [852 900 948]]

A * B + A * C:
[[222 234 246]
 [537 567 597]
 [852 900 948]]
Results are equal therefore: True


In [ ]:
#Commutative Property
import numpy as np

# Create matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create matrix B
B = np.array([[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]])

# Calculate A × B and B × A
AB = np.dot(A, B)  # A × B
BA = np.dot(B, A)  # B × A

# Display matrices A and B
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

# Display the results of A × B and B × A
print("\nA × B:")
print(AB)
print("\nB × A:")
print(BA)

# Check if A × B is equal to B × A (commutative property)
equal = np.array_equal(AB, BA)
print("\n A x B = B x A?", equal)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

A × B:
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]

B × A:
[[138 171 204]
 [174 216 258]
 [210 261 312]]

 A x B = B x A? False


In [1]:
#Identity Property
import numpy as np

# Define a 3x3 matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define the 3x3 identity matrix
B = np.identity(3)

# Multiply A by the identity matrix
AB = np.dot(A, B)

# Display matrix A,B,I
print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nMatrix AB (Identity matrix):")
print(AB)

# Check if AB = A
result = np.array_equal(AB, A)
print("AB = A?", result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matrix AB (Identity matrix):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
AB = A? True


In [ ]:
#Zero Property
import numpy as np

# Create a 3x3 matrix A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Create a 3x3 zero matrix
zero_matrix = np.zeros((3, 3))

# Calculate A × 0 and 0 × A
A_O = np.dot(A, zero_matrix)
O_A = np.dot(zero_matrix, A)

# Display matrix A,B,I
print("Matrix A:")
print(A)
print("\nMatrix O:")
print(zero_matrix)

# Display the results
print("\nA × 0:")
print(A_O)
print("\n0 × A:")
print(O_A)

is_A_O_zero = np.array_equal(A_O, zero_matrix)
print("\nIs A × 0 = 0?", is_A_O_zero)

Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix O:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A × 0:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

0 × A:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Is A × 0 = 0? True


In [ ]:
#Dimension property
import numpy as np

# Create a 3x4 matrix A
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Create a 4x3 matrix B
B = np.array([[13, 14, 15],
              [16, 17, 18],
              [19, 20, 21],
              [22, 23, 24]])

# Perform matrix multiplication (A * B)
result = np.dot(A, B)

# Display matrices A and B
print("Matrix A (3x4):")
print(A)
print("\nMatrix B (4x3):")
print(B)

# Display the result of A * B
print("\nResult of A * B (3x3):")
print(result)

print("\n(m x n)x(n x k) = m x k?")
print("\n(3 x 3)x(4 x 3) = 3 x 3?, True")

Matrix A (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Matrix B (4x3):
[[13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

Result of A * B (3x3):
[[190 200 210]
 [470 496 522]
 [750 792 834]]

(m x n)x(n x k) = m x k?

(3 x 3)x(4 x 3) = 3 x 3?, True
