<a href="https://colab.research.google.com/github/DESPI-Cj/58013-Linear-Algebra/blob/main/Python_Exercise_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

X = np.array([
    [1,1,1],
    [3,-2,-1],
    [-1,4,2]
], dtype=float)

Y = np.array([
    [1],
    [4],
    [-3]
],dtype=float)
print(X)
print(X.shape)
print(Y)
print(Y.shape)


[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]
(3, 3)
[[ 1.]
 [ 4.]
 [-3.]]
(3, 1)


So let's start off with an easy one. Let's say you have a bakery and you are purchasing supplies consisting of flour, yeast, and eggs from your supplier. For month 1 you bought a bakery promo that consists of 30 sacks of flour, 10 packs of yeast, and 120 eggs and you are charged for 12,500 pesos. For month two you bought a different bakery promo that consists of 40 sacks of flour, 20 packs of yeast, and 200 eggs then you are charged with 18,000 pesos. And then for month three you bought yet a different bakery promo that consists of 50 sacks of flour, 40 packs of yeast, and 360 eggs for 25,700 pesos. Now you are wondering if the promos are more cost-effective compared to buying them as a regular buyer, what could be the price of the flour per sack, yeast per pack, and one piece of egg?

	Create a python program to solve for the price of flour per sack, yeast per pack, and one piece of egg.


In [6]:
# 30x + 10y + 120z = 12,500
# 40x + 20Y + 200Z = 18,000
# 50x + 40y + 360z = 25,700
import numpy as np

A = np.array([
    [30, 10, 120],
    [40, 20, 200],
    [50, 40, 360]
])

B = np.array([12500, 18000, 25700])

# Solve the system of linear equations
solution = np.linalg.solve(A, B)

flour = int(solution[0])
yeast = int(solution[1])
eggs = int(solution[2])

print("The price of the flour per sack is", flour,"pesos")
print("The price of the yeast per pack is", yeast,"pesos")
print("The price of the egg per piece is", eggs,"pesos")

The price of the flour per sack is 330 pesos
The price of the yeast per pack is 139 pesos
The price of the egg per piece is 10 pesos
