<a href="https://colab.research.google.com/github/DESPI-Cj/58013-Linear-Algebra/blob/main/Vectors%2CSpace%2C_and_Operation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([4,3])
B = np.array([2, -5])
print('Vector A is ', A)
print('Vector B is ', B)

Vector A is  [4 3]
Vector B is  [ 2 -5]


In [ ]:
import numpy as np

# Define arrays
ball1 = np.array([1, 2, 3])
ball2 = np.array([0, -1, 1])

print(ball1)
print(ball2)

# Create a tuple containing the shapes of ball1 and ball2
shape_ball1 = (ball1.shape)
shape_ball2 = (ball2.shape)
combined_shape = shape_ball1 + shape_ball2

# Checking the combined shape
print(combined_shape)


[1 2 3]
[ 0 -1  1]
(3, 3)


Addition





In [ ]:
import numpy as np
R1 = np.array([4,3])
R2 = np.array([2,-5])
R = R1 + R2
print(R)

[ 6 -2]


Subtraction


In [28]:
import numpy as np
R1 = np.array([4,3])
R2 = np.array([2,-5])
Rab = np.subtract(R1,R2)
Rba = np.subtract(R2,R1)
print(Rab)
print(Rba)

[2 8]
[-2 -8]


Scalar Product

In [42]:
import numpy as np
S = np.array([2])
V = S*A
print(V)



[8 6]
[  8 -15]


Multiplication

In [49]:
import numpy as np
R1 = np.array([4, 3])
R2 = np.array(([2],[-5]))

print(R1*R2)

[[  8   6]
 [-20 -15]]


Dot Product

In [50]:
import numpy as np

R1 = np.array([4, 3])
R2 = np.array([2, -5])

dot_product = np.dot(R1, R2)
print(dot_product)



-7


Cross Product

In [51]:
import numpy as np

# Define two 3D vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the cross product
cross_product = np.cross(vector1, vector2)

print("Cross product:", cross_product)


Cross product: [-3  6 -3]


In [66]:
#Property of Matrix
#Identity Matrix

A = np.array([4,3])
B = np.array(((2),(-5)))

c = np.eye(3,3)
print(c)

#Zero Matrix
d = np.zeros([5,5])
print("\n",d)

#Full Matrix
e = np.full((3,3),7)
print("\n",e)

#Transpose Matrix
f = np.transpose(A)
print("\n",f,"\n")

#Empty Matrix
empty_array = np.empty((3, 3))
print(empty_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

 [[7 7 7]
 [7 7 7]
 [7 7 7]]

 [4 3] 

[[4.86081907e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]
